examples:
  - example/*
  - example/**/*

react:
  - packages/react/*
  - packages/react/**/*

core:
  - packages/core/*
  - packages/core/**/*

cypress:
  - cypress/*
  - cypress/**/*

repo:
  - ./*
