name: E2E Test
on: [pull_request]
jobs:
  cypress:
    name: Cypress
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm run start:app
          wait-on: 'http://localhost:1234'
          wait-on-timeout: 120
